I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 224, in script
    Андрей "Да, я готов."
Exception: Sayer 'Андрей' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 224, in script
    Андрей "Да, я готов."
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\4853597\Desktop\renPy\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Андрей' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Frontend Fantasy 1.0
Fri Dec  1 17:47:39 2023
